% S1a_TRANSMITTER controls the SDR transmit path and uplink acquisition.
% Downlink samples are generated by S1b_ACMControl.m and received through
% config.txBlockPort. In RF mode, uplink samples are processed through
% acquisition stages 1-5 and detected CLTUs are forwarded to S1b for
% derandomization, LDPC decoding, and command recovery.
% Each testbed script can be started independently because TCP clients
% retry until their corresponding server becomes available.

clear; clc;

% Add all project functions recursively, relative to this script's location.
addpath(genpath(fullfile(fileparts(mfilename('fullpath')), 'Functions')));

config = dvbs2TestbedConfig();

Fsamp = config.usrp.sampleRate;
txBlockSamples = config.tx.blockSamples;

% Initialize the dummy waveform cache before it is needed by the fallback path.
dvbs2DummyFiller(txBlockSamples, config.dvbs2.SamplesPerSymbol, config.dvbs2.RolloffFactor, 10);

% Limit the wait for S1b to leave time for transmission within the block period.
% If no block arrives, transmit a locally generated dummy waveform.
localDummyWaitThresholdSec = 0.85 * (txBlockSamples / Fsamp);

%% TX dispatch setup
if config.useSDR
    % Configure the USRP transmitter using the hardware-compatible sampling rate.
    radioTx = comm.SDRuTransmitter( ...
        'Platform', config.usrp.platform, ...
        'IPAddress', config.usrp.txIPAddress, ...
        'MasterClockRate', config.usrp.masterClockRate, ...
        'InterpolationFactor', config.usrp.inter_decimateFactor, ...
        'CenterFrequency', config.usrp.centerFrequency, ...
        'Gain', config.usrp.txGain);
    fprintf('S1a: transmitting via USRP at %s (CenterFrequency=%.3f MHz)\n', ...
        config.usrp.txIPAddress, config.usrp.centerFrequency/1e6);
    cleanupTx = onCleanup(@() release(radioTx));
else
    fprintf('S1a: connecting to S2a''s simulated-channel server at %s:%d ...\n', ...
        config.simChannelHost, config.simChannelPort);
    simChannelClient = dvbs2TCPConnectRetry( ...
        config.simChannelHost, config.simChannelPort, 'S2a''s simulated-channel server');
    fprintf('S1a: connected.\n');
    % The TCP connection is released automatically when the client variable
    % is cleared or goes out of scope. Transmission pacing is controlled by
    % the TX-block wait loop below.
end

%% Uplink radio (RF mode only) -- acquires CLTUs, forwards only what it finds
uplinkRF = config.useSDR && config.uplink.useRF;
uplinkOverruns = 0;
uplinkChunksRead = 0;
% Samples owed from the uplink radio but not yet read by this process.
uplinkDebtSamples = 0;
% Previous TX burst duration, used to pace uplink reads.
lastBurstSec = 0;

if uplinkRF
    u = config.uplink;
    radioUplinkRx = comm.SDRuReceiver( ...
        'Platform', config.usrp.platform, ...
        'IPAddress', u.rxIPAddress, ...
        'MasterClockRate', config.usrp.masterClockRate, ...
        'DecimationFactor', u.inter_decimateFactor, ...
        'CenterFrequency', u.centerFrequency, ...
        'Gain', u.rxGain, ...
        'OutputDataType', 'double', ...
        'SamplesPerFrame', u.rxFrameLength);
    cleanupUplinkRx = onCleanup(@() release(radioUplinkRx));
    fprintf('S1a: return link over RF -- receiving on %s at %.3f MHz, gain %g dB\n', ...
        u.rxIPAddress, u.centerFrequency/1e6, u.rxGain);

    % Reset persistent acquisition state before starting the receive loop.
    clear ccsdsUplinkAcquire ccsdsUplinkDCSuppress;
end

%% TX block input FROM S1b
% Start the TX block server before opening outbound connections to avoid
% circular waits during independent process startup.
fprintf('S1a: opening TX block listener on port %d ...\n', config.txBlockPort);
txBlockServer = dvbs2TCPServerRetry(config.txBlockHost, config.txBlockPort, "S1a's TX block server");
txBlockClientLogged = false;

if uplinkRF
    fprintf('S1a: connecting to S1b''s uplink acquisition server at %s:%d ...\n', ...
        config.uplinkAcqHost, config.uplinkAcqPort);
    uplinkAcqClient = dvbs2TCPConnectRetry( ...
        config.uplinkAcqHost, config.uplinkAcqPort, "S1b's uplink acquisition server");
    fprintf('S1a: connected to S1b.\n');
end

runTic = tic;
airtimeSec = 0;
prof = struct('uplinkRadio', 0, 'uplinkDSP', 0, 'uplinkForward', 0, 'blockWait', 0, 'radioTxTime', 0, ...
    'reads', 0, 'emptyReads', 0, 'iters', 0, 'underruns', 0, 'blocksReceived', 0, ...
    'localDummyBlocksSent', 0);
% Aggregate diagnostics for uplink acquisition stages 1-5.
uplinkWindows = 0;
uplinkDetections = 0;
uplinkAsmLocks = 0;
uplinkDuplicates = 0;
uplinkBestCarrierDB = -Inf;
uplinkBestASMMetric = 0;
uplinkCLTUsForwarded = 0;

fprintf('\nS1a: starting radio I/O loop (%d-sample blocks) ...\n', txBlockSamples);

while true

    %% Stop after config.runDurationSec and report where the time went
    if toc(runTic) >= config.runDurationSec
        wall = toc(runTic);
        fprintf('\n=== S1a PROFILE === %.1f s wall | %.1f s airtime | RT factor %.3f | %d iterations\n', ...
            wall, airtimeSec, wall/max(airtimeSec,eps), prof.iters);
        accounted = prof.uplinkRadio + prof.uplinkDSP + prof.uplinkForward + prof.blockWait + prof.radioTxTime;
        fprintf('  uplink radio reads   %7.2f s  %5.1f%%   %d reads (%d empty), %.1f ms each\n', ...
            prof.uplinkRadio, 100*prof.uplinkRadio/wall, prof.reads, prof.emptyReads, ...
            1e3*prof.uplinkRadio/max(prof.reads,1));
        fprintf('  uplink acquisition   %7.2f s  %5.1f%%   %d windows, %d detections, %d ASM locks, %d duplicates\n', ...
            prof.uplinkDSP, 100*prof.uplinkDSP/wall, uplinkWindows, uplinkDetections, uplinkAsmLocks, uplinkDuplicates);
        fprintf('  uplink forward to S1b %6.2f s  %5.1f%%   %d CLTUs forwarded\n', ...
            prof.uplinkForward, 100*prof.uplinkForward/wall, uplinkCLTUsForwarded);
        fprintf('  waiting for TX block %7.2f s  %5.1f%%   %d blocks received\n', ...
            prof.blockWait, 100*prof.blockWait/wall, prof.blocksReceived);
        fprintf('  radioTx              %7.2f s  %5.1f%%\n', ...
            prof.radioTxTime, 100*prof.radioTxTime/wall);
        fprintf('  everything else      %7.2f s  %5.1f%%\n', ...
            wall - accounted, 100*(wall - accounted)/wall);
        fprintf('  --\n');
        fprintf('  TX underruns %d of %d blocks | uplink RX overruns %d | local dummy fallback %d blocks (%.1f%%)\n', ...
            prof.underruns, prof.blocksReceived, uplinkOverruns, ...
            prof.localDummyBlocksSent, 100*prof.localDummyBlocksSent/max(prof.blocksReceived,1));
        fprintf('  uplink acquisition quality: best carrier %.1f dB, best ASM metric %.3f\n', ...
            uplinkBestCarrierDB, uplinkBestASMMetric);
        fprintf('  per iteration: %.1f ms wall, %.1f ms of airtime produced\n\n', ...
            1e3*wall/max(prof.iters,1), 1e3*airtimeSec/max(prof.iters,1));
        break;
    end
    prof.iters = prof.iters + 1;

    % Service MATLAB's event queue so asynchronous TCP connections are accepted.
    drawnow limitrate;

    %% Drain the uplink radio, acquire CLTUs, forward only what's found
    % Pace uplink reads according to the airtime produced by the TX path.
    if uplinkRF
        uplinkDebtSamples = min( ...
            uplinkDebtSamples + lastBurstSec * config.uplink.sampleRate, ...
            config.uplink.maxDrainReads * config.uplink.rxFrameLength);
        nUplinkReads = floor(uplinkDebtSamples / config.uplink.rxFrameLength);
        uplinkDebtSamples = uplinkDebtSamples - nUplinkReads * config.uplink.rxFrameLength;

        for k = 1:nUplinkReads
            tRead = tic;
            [uRx, uLen, uOvr] = radioUplinkRx();
            prof.uplinkRadio = prof.uplinkRadio + toc(tRead);
            prof.reads = prof.reads + 1;
            if uOvr
                uplinkOverruns = uplinkOverruns + 1;
            end
            if uLen == 0
                % No frame is currently available; continue on the next iteration.
                prof.emptyReads = prof.emptyReads + 1;
                break;
            end
            uplinkChunksRead = uplinkChunksRead + 1;

            % Process each sample chunk through acquisition stages 1-5.
            % Only detected CLTUs are forwarded to S1b.
            tDSP = tic;
            [cltus, aInfo] = ccsdsUplinkAcquire(uRx(1:uLen), config);
            prof.uplinkDSP = prof.uplinkDSP + toc(tDSP);
            uplinkWindows = uplinkWindows + aInfo.windows;
            uplinkDetections = uplinkDetections + aInfo.detections;
            uplinkAsmLocks = uplinkAsmLocks + aInfo.asmLocks;
            uplinkDuplicates = uplinkDuplicates + aInfo.duplicates;
            uplinkBestCarrierDB = max(uplinkBestCarrierDB, aInfo.bestCarrierDB);
            uplinkBestASMMetric = max(uplinkBestASMMetric, aInfo.bestASMMetric);

            tFwd = tic;
            for c = 1:numel(cltus)
                dvbs2TCPFrameWrite(uplinkAcqClient, dvbs2SerializeCLTU(cltus{c}));
                uplinkCLTUsForwarded = uplinkCLTUsForwarded + 1;
            end
            prof.uplinkForward = prof.uplinkForward + toc(tFwd);
        end
    end

    %% Wait for the next TX block from S1b -- non-blocking, with its own
    % Keep the wait non-blocking so the configured run duration is respected.
    if ~txBlockClientLogged && txBlockServer.Connected
        fprintf('S1a: S1b has connected to the TX block server.\n');
        txBlockClientLogged = true;
    end
    tWait = tic;
    txWaveform = complex([]);
    usedLocalDummy = false;
    while true
        blockBytes = dvbs2TCPFrameTryRead(txBlockServer);
        if ~isempty(blockBytes)
            txWaveform = dvbs2BytesToComplex(blockBytes);
            break;
        end
        if toc(runTic) >= config.runDurationSec
            break;   % The loop guard will report the profile and terminate.
        end
        if toc(tWait) >= localDummyWaitThresholdSec
            % Maintain continuous transmission if S1b does not provide a block.
            txWaveform = dvbs2DummyFiller(txBlockSamples, ...
                config.dvbs2.SamplesPerSymbol, config.dvbs2.RolloffFactor, 10);
            txWaveform = txWaveform(1:txBlockSamples);
            usedLocalDummy = true;
            break;
        end
        pause(0.001);
    end
    prof.blockWait = prof.blockWait + toc(tWait);
    if isempty(txWaveform)
        continue;
    end
    prof.blocksReceived = prof.blocksReceived + 1;
    if usedLocalDummy
        prof.localDummyBlocksSent = prof.localDummyBlocksSent + 1;
    end

    %% Transmit dispatch
    if config.useSDR
        tTx = tic;
        underrun = radioTx(txWaveform);
        prof.radioTxTime = prof.radioTxTime + toc(tTx);
        if underrun
            % Count underruns while avoiding repeated console output.
            prof.underruns = prof.underruns + 1;
            if prof.underruns == 1
                fprintf(2, 'S1a: TX underruns have started (block %d); counting silently from here.\n', ...
                    prof.blocksReceived);
            end
        end
    else
        % Send complex samples to S2a, which owns the simulated channel.
        % The samples are streamed without message framing.
        write(simChannelClient, dvbs2ComplexToBytes(txWaveform), 'uint8');
    end

    lastBurstSec = numel(txWaveform)/Fsamp;
    airtimeSec = airtimeSec + lastBurstSec;
    if mod(prof.blocksReceived, 10) == 0
        if uplinkRF
            fprintf(['S1a: block %d transmitted | RT factor %.3f | ' ...
                'uplink %d reads, %d CLTUs found, %d RX overruns\n'], ...
                prof.blocksReceived, toc(runTic)/max(airtimeSec,eps), ...
                uplinkChunksRead, uplinkCLTUsForwarded, uplinkOverruns);
        else
            fprintf('S1a: block %d transmitted | RT factor %.3f\n', ...
                prof.blocksReceived, toc(runTic)/max(airtimeSec,eps));
        end
    end
end
